### ISSUE TITLE
missing base file

### ISSUE THREAD

**Issue by wAOndering** [CYHSM/DeepInsight#3]
Hi,
The file in the jupyter notebook:
!wget https://ndownloader.figshare.com/files/20150468 -O ./example_data/processed_R2478.h5
is not available

**Comment by CYHSM** [comment]
The file is online for me, you can check if the command without specifying the output:
!wget https://ndownloader.figshare.com/files/20150468
The cell above this one creates the folder /example_data/ which is needed for the wget command to work

**Comment by wAOndering** [comment]
yes working now I must have done something wrong before with the creation of the folder. Thanks for the quick reply
